name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./*" # 你要上传的文件或目录
          target: "/GitOffice/19A/client" # 服务器上的目标路径
          #  替换nginx.conf指定root的html路径配置
          script: |
            sudo sed -i 's#GitOffice/19A#GitOffice/19A/client#g' /etc/nginx/nginx.conf
            sudo systemctl restart nginx
